name: inky
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0-165.1.beta <3.3.0"

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_riverpod: ^1.0.4
  freezed: null
  freezed_annotation: ^2.1.0
  go_router: ^5.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hooks_riverpod: ^1.0.4
  image_picker: ^0.8.5+3
  json_annotation: ^4.7.0
  json_serializable: ^6.4.0
  path_provider: ^2.0.11
  riverpod: ^1.0.3

dev_dependencies:
  build_runner: ^2.2.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3

flutter:
  uses-material-design: true
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  fonts:
    - family: Perandory
      fonts:
        - asset: assets/fonts/Perandory-Regular.otf
        - asset: assets/fonts/Perandory-Condensed.otf
          weight: 700

    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Regular.otf
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700

    - family: The Sans Typewriter
      fonts:
        - asset: assets/fonts/The Sans Typewriter-Regular.ttf
