name: inky
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0-165.1.beta <3.3.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  go_router: ^5.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  fonts:
    - family: Perandory
      fonts:
        - asset: assets/fonts/Perandory-Regular.otf
        - asset: assets/fonts/Perandory-Condensed.otf
          weight: 700

    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Regular.otf
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700

    - family: The Sans Typewriter
      fonts:
        - asset: assets/fonts/The Sans Typewriter-Regular.ttf
