// Mocks generated by Mockito 5.4.1 from annotations
// in inky/test/infrastructure/tags/tags_repository_test.dart.
// Do not manually edit this file.

// @dart=2.19

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:inky/infrastructure/tags/tag_dto.dart' as _i4;
import 'package:inky/infrastructure/tags/tags_local_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [TagsLocalService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTagsLocalService extends _i1.Mock implements _i2.TagsLocalService {
  MockTagsLocalService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i4.TagDto>> streamTags({List<_i4.TagDto>? filter}) =>
      (super.noSuchMethod(
        Invocation.method(
          #streamTags,
          [],
          {#filter: filter},
        ),
        returnValue: _i3.Stream<List<_i4.TagDto>>.empty(),
      ) as _i3.Stream<List<_i4.TagDto>>);
  @override
  _i3.Future<void> insert(_i4.TagDto? tagDto) => (super.noSuchMethod(
        Invocation.method(
          #insert,
          [tagDto],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
  @override
  _i3.Future<void> delete(_i4.TagDto? tagDto) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [tagDto],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
